name: Check Documentation Links

on:
  pull_request:
    paths: [ '**/*.md', 'docs/**' ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --cache --max-cache-age 1d '**/*.md'
          fail: true
          failIfEmpty: false
          token: ${{ secrets.GITHUB_TOKEN }}